services:
  postgres:
    image: postgres:16-alpine
    container_name: finbridge-postgres
    environment:
      POSTGRES_DB: finbridge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finbridge"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - finbridge-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: finbridge-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - finbridge-net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: finbridge-kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - finbridge-net

  api:
    build:
      context: .
      dockerfile: Finbridge.Api/Dockerfile
    container_name: finbridge-api
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=finbridge;Username=postgres;Password=postgres"
      BalanceSettings__MaxBalance: "1000000"
      KafkaSettings__BootstrapServers: "kafka:9092"
      KafkaSettings__Topic: "users.events"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health/live >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - finbridge-net

  backoffice:
    build:
      context: .
      dockerfile: Finbridge.Backoffice/Dockerfile
    container_name: finbridge-backoffice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=finbridge;Username=postgres;Password=postgres"
    ports:
      - "5000:8080"
    networks:
      - finbridge-net

networks:
  finbridge-net:
    driver: bridge

volumes:
  postgres_data:
